import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.io.File;
import java.util.Scanner;

public class SentinelDashboard {

    public static void main(String[] args) {
        JFrame frame = new JFrame("Sentinel-IOC - Professional Dashboard");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(900, 500);

        // 1. Table Setup
        String[] columns = {"Value", "Type", "Risk Score", "Country", "Action"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        JTable table = new JTable(model);

        // 2. Data Integration Logic (Reading from Python's output)
        try {
            // Path to the result file generated by Python
            File myFile = new File("../python-backend/result.json");
            Scanner reader = new Scanner(myFile);
            
            // For now, we print to console to verify the link
            System.out.println("[INFO] Loading data from: " + myFile.getAbsolutePath());
            
            // Note: In a real app, we use a JSON Parser. 
            // For learning, we will manually add the Python results we just generated.
            model.addRow(new Object[]{"185.156.177.10", "IPv4", "100", "NL", "BLOCK"});
            model.addRow(new Object[]{"192.168.1.105", "IPv4", "0", "Local", "CLEAN"});
            
            reader.close();
        } catch (Exception e) {
            System.out.println("[!] Error: Could not find result.json. Run Python script first!");
        }

        // 3. UI Layout
        frame.setLayout(new BorderLayout());
        JLabel header = new JLabel("Sentinel-IOC Real-time Threat Report", SwingConstants.CENTER);
        header.setFont(new Font("Arial", Font.BOLD, 18));
        
        frame.add(header, BorderLayout.NORTH);
        frame.add(new JScrollPane(table), BorderLayout.CENTER);

        frame.setVisible(true);
    }
}
